export const styles = {
  list: {
    padding: 0,
    width: '100%',
  },
  appbar: {
    position: 'static',
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#795548',
    boxShadow: '0px 3px 6px rgba(0,0,0,0.16), 0px 3px 6px rgba(0,0,0,0.23)',
  },
  title: {
    color: 'white',
    fontSize: 50,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  book: {
    width: 200,
    height: 400,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    margin: '10px 10px 0px 10px',
  },
  booktop: {
    position: 'relative',
  },
  bookCover: {
    boxShadow: '0px 3px 6px rgba(0,0,0,0.16), 0px 3px 6px rgba(0,0,0,0.23)',
    backgroundColor: '#eee',
    width: 128,
    height: 188,
    marginTop: 10,
  },
  bookCoverTitle: {
    padding: '20 10 0',
    textAlign: 'center',
    fontSize: 0.8,
  },
  bookTitle: {
    marginTop: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  bookAuthors: {
    color: '#999',
    textAlign: 'center',
  },
  listBooksTitle: {
    padding: '10 0',
    backgroundColor: '#2e7c31',
    textAlign: 'center',
  },
  listBooksContent: {
    flex: 1,
  },
  bookShelf: {
    padding: 25,
  },
  bookshelfTitle: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'black',
    backgroundColor: '#cb9b67',
    boxShadow: '0px 3px 6px rgba(0,0,0,0.16), 0px 3px 6px rgba(0,0,0,0.23)',
  },
  bookshelfBooks: {
    display: 'flex',
    justifyContent: 'center',
  },
  button: {
    width: 200,
    marginTop: 'auto',
    backgroundColor: '#795548',
    color: 'black',
    fontSize: 15,
    fontWeight: 'bold',
  },
  buttons: {
    backgroundColor: '#795548',
    color: 'black',
    fontWeight: 'bold',
  },
  searchbutton: {
    position: 'fixed',
    backgroundColor: '#795548',
    right: 25,
    bottom: 25,
  },
  bigImg: {
    height: 300,
    width: 180,
    margin: 10,
  },
  subtitle: {
    fontWeight: 'bold',
    fontSize: 35,
    textAlign: 'center',
    paddin: 10,
  },
  searchBooksBar: {
    width: '100%',
    top: 10,
    left: 0,
    zIndex: '5',
    paddingTop: '10',
    display: 'flex',
    boxShadow: '0 10px 20px rgba(0,0,0,0.19), 0 0 6px rgba(0,0,0,0.23)',
  },
  textField: {
    backgroundColor: 'white',
    width: '100%',
    padding: '15px 10px',
    fontSize:'1.5em',
    border: 'none',
    outline: 'none',
  },
  searchBooksResults: {
    padding: '40px 30px 40px 30px',
  },
  booksGrid: {
    listStyleType: 'none',
    padding: 10,
    margin: '0',
    display: 'flex',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  bookRatingContainer: {
    listStyleType: 'none',
    fontSize: '13px',
    fontWeight: 'bold',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bookRatingCounter: {
    fontSize: '12px',
    display: 'inline-block',
    lineHeight: 'normal',
    paddingTop: '5px',
  },
  loading: {
    position: 'fixed',
    left:'50%',
    top:'50%',
    width: '100px',
    height: '100px',
    margin: '-50px 0px 0px -50px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#795548',
    fontSize: '50px',
  },
  backButton: {
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: '30px',
  },
  writtenBy: {
    fontSize: 20,
    textAlign: 'right',
    marginRight: 10,
  },
  publishedBy: {
    fontSize: 20,
    textAlign: 'right',
    marginRight: 10,
  },
  description: {
    fontSize: 17,
    textAlign: 'justify',
    marginRight: 10,
  },
  bookCard: {
    width: '85%',
    height: '85%',
  },
  bookInfo: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 10,
  },
  bookDetails: {
    width: '85%',
    height: '85%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '10px 10px 0px 10px',
  },
  bookinfoTitle: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'black',
    backgroundColor: '#cb9b67',
    boxShadow: '0px 3px 6px rgba(0,0,0,0.16), 0px 3px 6px rgba(0,0,0,0.23)',
  },
  back: {
    position: 'fixed',
    backgroundColor: '#795548',
    right: 45,
    bottom: 25,
  }
}
